### ISSUE TITLE
What is the difference between OWM and GEM algorithm?

### ISSUE THREAD

**Issue by Yue-Liu** [beijixiong3510/OWM#1]
Hi, I have two questions about your work:
1. What is the difference between OWM and [GEM algorithm](http://papers.nips.cc/paper/7225-gradient-episodic-memory-for-continual-learning.pdf)? GEM projects the gradient on the subspace of gradients from old samples. Is the subspace of inputs x better for solving continual learning problem?

2. Why should we update p before projecting the gradient?
 `p.sub_(torch.mm(k, torch.t(k)) / (alpha + torch.mm(r, k)))`
`w.grad.data = torch.mm(w.grad.data, torch.t(p.data))`
This means the gradient is orthogonal to the subspace of new task and will affect the performance of on the new task.

Thank you.

[1] Lopez-Paz, David. "Gradient episodic memory for continual learning." NIPS. 2017.

**Comment by beijixiong3510** [comment]
1. A similar approach is proposed by Lopez-Paz et al. (2017), however instead of storing examples, gradients of the previous task are stored, such that at any point in time the gradients of all tasks except the current one can be used to form a trust region that prevents forgetting. Such methods can be effective against catastrophic forgetting, provided a good mechanism for the selection of relevant experience is proposed. An inherent problem is the constraint on the amount of experience that can be stored in memory, which could quickly become a limiting factor in large scale problems.(Please refer to http://proceedings.mlr.press/v80/schwarz18a/schwarz18a.pdf
Progress & Compress: A scalable framework for continual learning)
2. The order doesn't matter, because it's an iterative algorithm.
